# Tap
tap "nikitabobko/tap"

# Formulae
# brew "fd"
# brew "fzf"
# brew "gnupg"
brew "go"
brew "mas"
# brew "neovim"
# brew "ripgrep"
brew "stow"
# brew "tmux"
brew "uv"
brew "volta"
# brew "zoxide"

# Casks
cask "aerospace"
# cask "brave-browser"
# cask "ghostty"
cask "hyperkey"
# cask "scroll-reverser"
# cask "zed"

# App Store
mas "Velja", id: 1607635845
