[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "None"
opacity = 0.33
blur = true
option_as_alt = "Both"

[font]
normal = { family = "SF Mono", style = "Regular" }
size = 14

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Never" }

[terminal]
osc52 = "CopyPaste"

# [keyboard]
