" Core settings
set nocompatible
set nolangremap
let g:is_posix = 1

" Basic editing behavior
set backspace=indent,eol,start
set complete-=i
set clipboard=unnamed
set smarttab
set nrformats-=octal
set incsearch
set autoread
set history=1000
set tabpagemax=50

" Display and UI
set ruler
set laststatus=2
set wildmenu
set scrolloff=1
set sidescroll=1
set sidescrolloff=2
set display+=lastline
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set formatoptions+=j
set t_Co=16
set ttimeout
set ttimeoutlen=100

" File/session management
setglobal tags-=./tags; tags^=./tags;
set sessionoptions-=options
set viewoptions-=options
set noswapfile
set nobackup
set nowritebackup
set noundofile
set viminfo+=n$XDG_STATE_HOME/viminfo

" Key mappings
nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
inoremap <C-U> <C-G>u<C-U>
inoremap <C-W> <C-G>u<C-W>

" Custom commands
command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_
    \ | diffthis | wincmd p | diffthis

" Runtime and plugins
filetype plugin indent on
syntax enable
runtime! macros/matchit.vim
runtime ftplugin/man.vim

" Colorscheme
colorscheme snazzy
let g:SnazzyTransparent = 0
