live_config_reload = true

import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[keyboard]
bindings = [
  { key = "W", mods = "Command", action = "None" },  # Disable Command + W (Close window)
  # { key = "N", mods = "Command", action = "None" },  # Disable Command + N (Create new instance)
  # { key = "B", mods = "Alt", chars = "\u001BB" },  # Alt + B (Move backward one word)
  # { key = "F", mods = "Alt", chars = "\u001BF" },  # Alt + F (Move forward one word)
  # { key = "D", mods = "Alt", chars = "\u001BD" },  # Alt + D (Delete the word after the cursor)
  # { key = "Backspace", mods = "Alt", chars = "\u001B\u007F" },  # Alt + Backspace (Delete word before cursor)
  # { key = "U", mods = "Alt", chars = "\u001BU" },  # Alt + U (Uppercase from cursor to end of word)
  # { key = "L", mods = "Alt", chars = "\u001BL" },  # Alt + L (Lowercase from cursor to end of word)
  # { key = "C", mods = "Alt", chars = "\u001BC" },  # Alt + C (Capitalize the current word)
  # { key = ".", mods = "Alt", chars = "\u001B." },  # Alt + . (Insert the last argument of previous command)
  # { key = "Y", mods = "Alt", chars = "\u001BY" },  # Alt + Y (Yank the top of the kill-ring)
  # { key = "T", mods = "Alt", chars = "\u001BT" },  # Alt + T (Transpose the words around cursor)
  # { key = "R", mods = "Alt", chars = "\u001BR" },  # Alt + R (Recall the last command that matches input)
  # { key = "N", mods = "Alt", chars = "\u001BN" },  # Alt + N (Search forward through history)
  # { key = "P", mods = "Alt", chars = "\u001BP" },  # Alt + P (Search backward through history)
]

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["-u", "new", "-A"]

[window]
decorations = "Buttonless"
opacity = 1.00
startup_mode = "Windowed"
option_as_alt = "OnlyLeft"
dynamic_padding = true

#[window.dimensions]
#columns = 80
#lines = 60

[window.padding]
x = 8
y = 8
